config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'welcome/index'

  get '/documents/archive', to: 'documents#archive', as: 'archive'
  
  resources :documents
  resources :categories

  authenticated :user do
    root to: "documents#index", as: "authenticated_root"
  end

  root to: "welcome#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :documents

end

app/models/document.rb
class Document < ApplicationRecord

  acts_as_paranoid

  belongs_to :user

  belongs_to :category, required: false
  attr_accessor :new_category_name
  before_save :create_category_from_name

  def create_category_from_name
    create_category(name: new_category_name) unless new_category_name.blank?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :documents

  has_many :categories, through: :documents
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @documents = Document.where(user_id: current_user)
    @user = current_user
    @categories = @user.categories.order(:name)
  end

  def show
    @documents = Document.where(user_id: current_user)
    @user = current_user
    @categories = @user.categories.order(:name)
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.where(user_id: current_user)
    @user = current_user
    @categories = @user.categories.order(:name)
    @deleted_documents = Document.only_deleted.where(user_id: current_user)
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = current_user.documents.build
    @user = current_user
    @categories = @user.categories.order(:name)
  end

  # GET /documents/1/edit
  def edit
    @user = current_user
    @categories = @user.categories.order(:name)
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = current_user.documents.build(document_params)
    @user = current_user
    @categories = @user.categories.order(:name)

    respond_to do |format|
      if @document.save
        format.html { render :edit, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    @user = current_user
    @categories = @user.categories.order(:name)

    respond_to do |format|
      if @document.update(document_params)
        format.html { render :edit }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @user = current_user
    @document = @user.documents.with_deleted.find(params[:id])

    if params[:type] == nil
      @document.destroy
    elsif params[:type] == 'forever'
      @document.really_destroy!
    elsif params[:type] == 'undelete'
      @document.restore
    end

    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document archived.' }
      format.json { head :no_content }
    end
  end

  def archive
    @document = Document.only_deleted.where(user_id: current_user)
    @documents = Document.only_deleted.where(user_id: current_user)
    @all_documents = Document.where(user_id: current_user)
    @user = current_user
    @categories = @user.categories.order(:name)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:title, :content, :category_id, :new_category_name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def browser_title(page_title)
    content_for(:browser_title) { page_title }
  end

  def active_class(link_path)
    current_page?(link_path) ? "link--highlighted" : ""
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/show.html.erb
<!-- Desktop tags index -->
<nav class="tags-index--desktop fixed top--0 bottom--0 left--0 bg--dark-tan hide-on-mobile">
  <div class="tag-container pt2">

    <h1 class="mb0">
      <a href="/" class="link link--text monospace pl2 pr2 block mb2">
        <%= image_tag "paperclip_logo.svg", class: "logo", alt: "Paperclip" %>
      </a>
    </h1>

    <!-- Tags -->
    <ul class="no-bullets">
      <li>
        <%= link_to root_path, class: 'link link--highlight pl2 pr2 pts pbs block' do %>
          <div class="grid-row">
            <span class="grid-column ellipsis pr0">All</span>
            <span class="grid-column span-3 align--right pl0"><%= @documents.count %></span>
          </div>
        <% end %>
      </li>
      <% @categories.uniq.each do |category| %>
        <li class="<%= active_class(category_path(category)) %>">
          <%= link_to category_path(category), class: 'link link--highlight pl2 pr2 pts pbs block' do %>
            <div class="grid-row">
              <span class="grid-column ellipsis pr0"><%= category.name %></span>
              <span class="grid-column span-3 align--right pl0"><%= category.documents.where(user_id: current_user).count %></span>
            </div>
          <% end %>
        </li>
      <% end %>

      <li>
        <%= link_to archive_path, class: 'link link--highlight pl2 pr2 pts pbs block' do %>
          <div class="grid-row">
            <span class="grid-column">Archived</span>
            <span class="grid-column span-3 align--right"></span>
          </div>
        <% end %>
      </li>

    </ul>

  </div>

  <!-- Settings -->
  <div class="fixed bottom--0 left--0">
      <div class="link link--text p2 js-popup-toggle"><i data-feather="settings"></i></div>
      <!-- Popup -->
      <div class="settings-popup absolute border--full rounded full-shadow bg--white js-popup">
        <%= link_to edit_user_registration_path, class: 'link link--highlight block mb0 pl1 pr1 pts pbs border--bottom' do %>
            <i data-feather="user" class="vertical--text-top"></i>&nbsp;&nbsp;Account
          <% end %>
          <%= link_to(destroy_user_session_path, method: :delete, class: "link link--highlight block mb0 pl1 pr1 pts pbs") do %>
            <i data-feather="log-out" class="vertical--text-top"></i>&nbsp;&nbsp;Log Out
          <% end %>
      </div>
  </div>
    
</nav>

<!-- Mobile tags index -->
<nav class="tags-index--mobile bg--dark-tan pts pbs show-on-mobile">
    <div class="container">
        <div class="clearfix">
            <h1 class="mb0 float--left">
              <a href="/" class="link link--text monospace">
                <%= image_tag "paperclip_logo.svg", class: "logo--mobile relative", alt: "Paperclip" %>
              </a>
            </h1>
            <div class="mobile-menu-icon float--right pl3 relative js-slidedown-toggle">
                <span class="vertical--top">All</span> <i data-feather="menu" class="ml1"></i>
            </div>
        </div>
    </div>
    <div class="tags-index__mobile-nav js-slidedown">
        <ul class="no-bullets border--top pt1 mts">
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">All</a>
            </li>
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">blog</a>
            </li>
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">business</a>
            </li>
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">essays</a>
            </li>
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">journal</a>
            </li>
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">Archived</a>
            </li>
        <ul class="no-bullets border--top pt1 mt1">
            <li>
                <a href="settings.html" class="link link--highlight block pl2 pr2 pts pbs">Account</a>
            </li>
            <li>
                <a href="" class="link link--highlight block pl2 pr2 pts pbs">Log Out</a>
            </li>
        </ul>
    </div>
</nav>

<!-- Documents index -->
<div class="documents-index p2">
  <div class="pb2">

    <!-- New -->
    <div class="mb2">
      <%= link_to new_document_path, class: 'btn btn--default' do %>
        <i data-feather="plus" class="vertical--text-top relative" style="bottom:1px;"></i><span> New</span>
      <% end %>
    </div>

    <!-- Documents -->
    <div class="border--top">
      <% @category.documents.each do |document| %>
        <div class="border--bottom">
          <div class="grid-row grid-row--center">
            <div class="grid-column ellipsis">
              <h4 class="mb0 ellipsis">
                <%= link_to edit_document_path(document), class: 'link link--text block pt2 pb2' do %>
                  <%= document.title %>
                <% end %>
              </h4>
            </div>
            <div class="grid-column span-3 align--right">
              <%= link_to edit_document_path(document), class: 'link mr2', title: "Edit" do %>
                <i data-feather="edit" class="vertical--text-top"></i>
              <% end %>
              <%= link_to document, method: :delete, class: "link", title: "Archive" do %>
                <i data-feather="archive" class="vertical--text-top"></i>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/documents/_form.html.erb
<div class="container pt3 pb4">

  <%= form_with(model: document, local: true, id: "content") do |form| %>

    <!-- Document buttons -->
    <div class="document-menu pb2 text--lightest-gray">
      <div class="inline-block-on-mobile">
        <%= link_to root_path, class: 'link link--lightest-gray p1', title: "Back" do %>
          <i data-feather="arrow-left"></i>
        <% end %>
      </div>
      <div class="inline-block-on-mobile">
        <div class="link link--lightest-gray p1 js-modal-toggle" title="Front Matter"><i data-feather="info"></i></div>
      </div>
      <div class="inline-block-on-mobile">
        <%= link_to "", :onclick => "$('#content').submit()", class: 'link link--lightest-gray p1', title: "Save" do %>
          <i data-feather="save"></i>
        <% end %>
      </div>
    </div>

    <!-- Explain errors -->
    <% if document.errors.any? %>
      <div class="snack-bar fixed bottom--0 z5 full-shadow bg--primary-color rounded--top pt1 pb1 pl3 pr3 text--white none js-snack-bar">
        <p class="snack-bar__text align--center pl1 pr1 mb0"><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved: <%= message %></p>
      </div>
    <% end %>

    <!-- Editor -->
    <%= form.text_area :content, class: "form-control textarea--invisible mb3", id: "inscrybmde" %>

  <% end %>

</div>

app/views/documents/archive.html.erb
<% browser_title "Archive" %>

<!-- Desktop tags index -->
<nav class="tags-index--desktop fixed top--0 bottom--0 left--0 bg--dark-tan hide-on-mobile">
  <div class="tag-container pt2">

    <h1 class="mb0">
      <a href="/" class="link link--text monospace pl2 pr2 block mb2">
        <%= image_tag "paperclip_logo.svg", class: "logo", alt: "Paperclip" %>
      </a>
    </h1>

    <!-- Tags -->
    <ul class="no-bullets">
      <li>
        <%= link_to root_path, class: 'link link--highlight pl2 pr2 pts pbs block' do %>
          <div class="grid-row">
            <span class="grid-column ellipsis pr0">All</span>
            <span class="grid-column span-3 align--right pl0"><%= @all_documents.count %></span>
          </div>
        <% end %>
      </li>
      <% @categories.uniq.each do |category| %>
        <li>
          <%= link_to category_path(category), class: 'link link--highlight pl2 pr2 pts pbs block' do %>
            <div class="grid-row">
              <span class="grid-column ellipsis pr0"><%= category.name %></span>
              <span class="grid-column span-3 align--right pl0"><%= category.documents.where(user_id: current_user).count %></span>
            </div>
          <% end %>
        </li>
      <% end %>

      <li>
        <%= link_to archive_path, class: 'link link--highlight link--highlighted pl2 pr2 pts pbs block' do %>
          <div class="grid-row">
            <span class="grid-column">Archived</span>
            <span class="grid-column span-3 align--right"></span>
          </div>
        <% end %>
      </li>
    </ul>

  </div>

  <!-- Settings -->
  <div class="fixed bottom--0 left--0">
      <div class="link link--text p2 js-popup-toggle"><i data-feather="settings"></i></div>
      <!-- Popup -->
      <div class="settings-popup absolute border--full rounded full-shadow bg--white js-popup">
        <%= link_to edit_user_registration_path, class: 'link link--highlight block mb0 pl1 pr1 pts pbs border--bottom' do %>
            <i data-feather="user" class="vertical--text-top"></i>&nbsp;&nbsp;Account
          <% end %>
          <%= link_to(destroy_user_session_path, method: :delete, class: "link link--highlight block mb0 pl1 pr1 pts pbs") do %>
            <i data-feather="log-out" class="vertical--text-top"></i>&nbsp;&nbsp;Log Out
          <% end %>
      </div>
  </div>
    
</nav>

<!-- Mobile tags index -->
<nav class="tags-index--mobile bg--dark-tan pts pbs show-on-mobile">
    <div class="container">
        <div class="clearfix">
            <h1 class="mb0 float--left">
              <a href="/" class="link link--text monospace">
                <%= image_tag "paperclip_logo.svg", class: "logo--mobile relative", alt: "Paperclip" %>
              </a>
            </h1>
            <div class="mobile-menu-icon float--right pl3 relative js-slidedown-toggle">
                <span class="vertical--top">All</span> <i data-feather="menu" class="ml1"></i>
            </div>
        </div>
    </div>
    <div class="tags-index__mobile-nav js-slidedown">
        <ul class="no-bullets border--top pt1 mts">
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">All</a>
            </li>
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">blog</a>
            </li>
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">business</a>
            </li>
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">essays</a>
            </li>
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">journal</a>
            </li>
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">Archived</a>
            </li>
        <ul class="no-bullets border--top pt1 mt1">
            <li>
                <a href="settings.html" class="link link--highlight block pl2 pr2 pts pbs">Account</a>
            </li>
            <li>
                <a href="" class="link link--highlight block pl2 pr2 pts pbs">Log Out</a>
            </li>
        </ul>
    </div>
</nav>

<!-- Documents index -->
<div class="documents-index p2">
  <div class="pb2">

    <!-- New -->
    <div class="mb2">
      <%= link_to new_document_path, class: 'btn btn--default' do %>
        <i data-feather="plus" class="vertical--text-top relative" style="bottom:1px;"></i><span> New</span>
      <% end %>
    </div>

    <!-- Documents -->
    <div class="border--top">
      <% @documents.only_deleted.each do |document| %>
        <div class="border--bottom">
          <div class="grid-row grid-row--center">
            <div class="grid-column ellipsis">
              <h4 class="mb0 ellipsis">
                <div class="pt2 pb2">
                  <%= document.title %>
                </div>
              </h4>
            </div>
            <div class="grid-column span-3 align--right">
              <%= link_to document_path(document, type: :undelete), method: :delete, class: 'link mr2', title: "Restore" do %>
                <i data-feather="folder-plus" class="vertical--text-top"></i>
              <% end %>
              <%= link_to document_path(document, type: :forever), method: :delete, data: { confirm: 'Are you sure? Deleting documents is permanent.' }, class: "link", title: "Permanently Delete" do %>
                <i data-feather="trash" class="vertical--text-top"></i>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/documents/edit.html.erb
<% @browser_tab_title="Edit" %>

<%= render 'form', document: @document %>

<!-- Front matter modal -->
<div class="modal-background js-modal">
  <div class="modal full-shadow p2">
    <h3 class="pbs">Document Front Matter</h3>

    <%= form_with(model: @document, local: true) do |form| %>
      <div class="mb1">
        <%= form.label :title, class: "label" %>
        <%= form.text_field :title, class: "form-control", placeholder: "Title..." %>
      </div>
      <div class="mb1">
        <label class="label block" for="product_category_id">Choose exisiting category:</label>
        <div class="select">
          <%= form.collection_select :category_id, @categories.uniq, :id, :name, :prompt => "Select a Category" %>
        </div>
      </div>
      <div class="mb2">
        <p class="mb0">Or create one:</p>
        <%= form.text_field :new_category_name, class: "form-control" %>
      </div>
      <div class="clearfix">
        <%= form.submit "Save", class: "btn btn--default float--right" %>
        <a class="btn btn--outline float--right mr1 js-modal-close">Cancel</a>
      </div>

      <!-- Explain errors -->
      <% if @document.errors.any? %>
        <div class="snack-bar fixed bottom--0 z5 full-shadow bg--primary-color rounded--top pt1 pb1 pl3 pr3 text--white none js-snack-bar">
          <p class="snack-bar__text align--center pl1 pr1 mb0"><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved: <%= message %></p>
        </div>
      <% end %>

    <% end %>

  </div>
</div>

app/views/documents/index.html.erb
<% browser_title "Home" %>

<!-- Desktop tags index -->
<nav class="tags-index--desktop fixed top--0 bottom--0 left--0 bg--dark-tan hide-on-mobile">
  <div class="tag-container pt2">

    <h1 class="mb0">
      <a href="/" class="link link--text monospace pl2 pr2 block mb2">
        <%= image_tag "paperclip_logo.svg", class: "logo", alt: "Paperclip" %>
      </a>
    </h1>

    <!-- Tags -->
    <ul class="no-bullets">
      <li>
        <%= link_to root_path, class: 'link link--highlight link--highlighted pl2 pr2 pts pbs block' do %>
          <div class="grid-row">
            <span class="grid-column ellipsis pr0">All</span>
            <span class="grid-column span-3 align--right pl0"><%= @documents.count %></span>
          </div>
        <% end %>
      </li>

      <% @categories.uniq.each do |category| %>
        <li>
          <%= link_to category_path(category), class: 'link link--highlight pl2 pr2 pts pbs block' do %>
            <div class="grid-row">
              <span class="grid-column ellipsis pr0"><%= category.name %></span>
              <span class="grid-column span-3 align--right pl0"><%= category.documents.where(user_id: current_user).count %></span>
            </div>
          <% end %>
        </li>
      <% end %>

      <li>
        <%= link_to archive_path, class: 'link link--highlight pl2 pr2 pts pbs block' do %>
          <div class="grid-row">
            <span class="grid-column">Archived</span>
            <span class="grid-column span-3 align--right"></span>
          </div>
        <% end %>
      </li>
    </ul>

  </div>

  <!-- Settings -->
  <div class="fixed bottom--0 left--0">
      <div class="link link--text p2 js-popup-toggle"><i data-feather="settings"></i></div>
      <!-- Popup -->
      <div class="settings-popup absolute border--full rounded full-shadow bg--white js-popup">
        <%= link_to edit_user_registration_path, class: 'link link--highlight block mb0 pl1 pr1 pts pbs border--bottom' do %>
            <i data-feather="user" class="vertical--text-top"></i>&nbsp;&nbsp;Account
          <% end %>
          <%= link_to(destroy_user_session_path, method: :delete, class: "link link--highlight block mb0 pl1 pr1 pts pbs") do %>
            <i data-feather="log-out" class="vertical--text-top"></i>&nbsp;&nbsp;Log Out
          <% end %>
      </div>
  </div>
    
</nav>

<!-- Mobile tags index -->
<nav class="tags-index--mobile bg--dark-tan pts pbs show-on-mobile">
    <div class="container">
        <div class="clearfix">
            <h1 class="mb0 float--left">
              <a href="/" class="link link--text monospace">
                <%= image_tag "paperclip_logo.svg", class: "logo--mobile relative", alt: "Paperclip" %>
              </a>
            </h1>
            <div class="mobile-menu-icon float--right pl3 relative js-slidedown-toggle">
                <span class="vertical--top">All</span> <i data-feather="menu" class="ml1"></i>
            </div>
        </div>
    </div>
    <div class="tags-index__mobile-nav js-slidedown">
        <ul class="no-bullets border--top pt1 mts">
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">All</a>
            </li>
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">blog</a>
            </li>
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">business</a>
            </li>
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">essays</a>
            </li>
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">journal</a>
            </li>
            <li class="">
                <a href="" class="link link--highlight pl2 pr2 pts pbs block">Archived</a>
            </li>
        <ul class="no-bullets border--top pt1 mt1">
            <li>
                <a href="settings.html" class="link link--highlight block pl2 pr2 pts pbs">Account</a>
            </li>
            <li>
                <a href="" class="link link--highlight block pl2 pr2 pts pbs">Log Out</a>
            </li>
        </ul>
    </div>
</nav>

<!-- Documents index -->
<div class="documents-index p2">
  <div class="pb2">

    <!-- New -->
    <div class="mb2">
      <%= link_to new_document_path, class: 'btn btn--default' do %>
        <i data-feather="plus" class="vertical--text-top relative" style="bottom:1px;"></i><span> New</span>
      <% end %>
    </div>

    <!-- Documents -->
    <div class="border--top">
      <% @documents.each do |document| %>
        <div class="border--bottom">
          <div class="grid-row grid-row--center">
            <div class="grid-column ellipsis">
              <h4 class="mb0 ellipsis">
                <%= link_to edit_document_path(document), class: 'link link--text block pt2 pb2' do %>
                  <%= document.title %>
                <% end %>
              </h4>
            </div>
            <div class="grid-column span-3 align--right">
              <%= link_to edit_document_path(document), class: 'link mr2', title: "Edit" do %>
                <i data-feather="edit" class="vertical--text-top"></i>
              <% end %>
              <%= link_to document, method: :delete, class: "link", title: "Archive" do %>
                <i data-feather="archive" class="vertical--text-top"></i>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/documents/new.html.erb
<% browser_title "New" %>

<%= render 'form', document: @document %>

<!-- Front matter modal -->
<div class="modal-background js-modal" style="display: block;">
  <div class="modal full-shadow p2">
    <h3 class="pbs">Write a title</h3>

    <%= form_with(model: @document, local: true) do |form| %>
      <div class="mb1">
        <%= form.text_field :title, class: "form-control", placeholder: "Title..." %>
      </div>
      <div class="clearfix">
        <%= form.submit "Save", class: "btn btn--default float--right" %>
        <%= link_to 'Cancel', root_path, class: "btn btn--outline float--right mr1" %>
      </div>

      <!-- Explain errors -->
      <% if @document.errors.any? %>
        <div class="snack-bar fixed bottom--0 z5 full-shadow bg--primary-color rounded--top pt1 pb1 pl3 pr3 text--white none js-snack-bar">
          <p class="snack-bar__text align--center pl1 pr1 mb0"><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved: <%= message %></p>
        </div>
      <% end %>

    <% end %>

  </div>
</div>

app/views/documents/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @document.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @document.content %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/welcome/index.html.erb
<div class="container pt3 pb3">
  <h1>Welcome placeholder</h1>
  <p>Find me in app/views/welcome/index.html.erb</p>
  
  <%= link_to('Sign Up', new_user_registration_path, class: "btn btn--default")  %>
  <%= link_to('Login', new_user_session_path, class: "btn btn--outline")  %>
</div>